# A string used to identify the project.
project_id = "split-up"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public"]

[db]
port = 54322

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false
